spring.application.name=todoList
spring.datasource.url=jdbc:mysql://localhost:3306/todoList_DB

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
